name       : haskell-generic-deriving
version    : 1.11.1
release    : 1
source     :
    - http://hackage.haskell.org/package/generic-deriving-1.11.1/generic-deriving-1.11.1.tar.gz : b38d427f990f3080108c565a81284217290a47be63bab7bf59036ece2e2cb0e9
license    : BSD-3-Clause
component  : programming.haskell
summary    : This package provides functionality for generalising the deriving mechanism in Haskell to arbitrary classes.
description: |
    This package provides functionality for generalising the deriving mechanism in Haskell to arbitrary classes.
builddeps  :
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
