name       : haskell-generic-deriving
version    : 1.13.1
release    : 4
source     :
    - https://hackage.haskell.org/package/generic-deriving-1.13.1/generic-deriving-1.13.1.tar.gz : e9b53a40eae58e18ee281858a1ba400f14128d5779858272b01c10d64aa09abe
license    : BSD-3-Clause
component  : programming.haskell
summary    : This package provides functionality for generalising the deriving mechanism in Haskell to arbitrary classes.
description: |
    This package provides functionality for generalising the deriving mechanism in Haskell to arbitrary classes.
builddeps  :
    - haskell-cabal-install
    - haskell-th-abstraction-devel
rundeps    :
    - devel:
        - haskell-th-abstraction-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
