name       : haskell-generic-deriving
version    : 1.12.1
release    : 2
source     :
    - https://hackage.haskell.org/package/generic-deriving-1.12.1/generic-deriving-1.12.1.tar.gz : f5fd3f733a20deee5a6e752969edac1e04a90e2ee34e005fccb5d35a5c129473
license    : BSD-3-Clause
component  : programming.haskell
summary    : This package provides functionality for generalising the deriving mechanism in Haskell to arbitrary classes.
description: |
    This package provides functionality for generalising the deriving mechanism in Haskell to arbitrary classes.
builddeps  :
    - ghc
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
